version: '3'

services:
  traefik:
    image: traefik:v2.4
    container_name: traefikk
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik-proxy
      - web
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /root/traefic-dolibarr/traefik-data/traefik.yml:/traefik.yml:ro
      - /root/traefic-dolibarr/traefik-data/acme.json:/acme.json
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=http"
      - "traefik.http.routers.traefik.rule=Host(`vps13pruxweb09.newtoncorp.fr`)"
      - "traefik.http.middlewares.traefik-auth.basicauth.users=lefree:$$apr1$$R7SIqDPb$$58ZeDvOU6ADPjdCLmqIWe/"
      - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.traefik.middlewares=traefik-https-redirect"
      - "traefik.http.routers.traefik-secure.entrypoints=https"
      - "traefik.http.routers.traefik-secure.rule=Host(`vps13pruxweb09.newtoncorp.fr`)"
      - "traefik.http.routers.traefik-secure.middlewares=traefik-auth"
      - "traefik.http.routers.traefik-secure.tls=true"
      - "traefik.http.routers.traefik-secure.tls.certresolver=http"
      - "traefik.http.routers.traefik-secure.service=api@internal"

  portainer:
    image: portainer/portainer:latest
    container_name: portainer
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik-proxy
    ports:
      - 8000:8000
      - 9000:9000      
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /root/traefik-portenaire/trafik-data/portainer-data:/data
#    labels:
#      - "traefik.enable=true"
#      - "traefik.http.routers.portainer.entrypoints=http"
#      - "traefik.http.routers.portainer.rule=Host(`dolivps.newtoncorp.fr`)"
#      - "traefik.http.middlewares.portainer-https-redirect.redirectscheme.scheme=https"
#      - "traefik.http.routers.portainer.middlewares=traefik-https-redirect"
#      - "traefik.http.routers.portainer-secure.entrypoints=https"
#      - "traefik.http.routers.portainer-secure.rule=Host(`dolivps.newtoncorp.fr`)"
#      - "traefik.http.routers.portainer-secure.tls=true"
#      - "traefik.http.routers.portainer-secure.tls.certresolver=http"
     
#      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
#      - "traefik.docker.network=traefik-proxy"
#      - "traefik.http.routers.portainer-secure.service=portainer"
      
  
  bitwarden:
    image: bitwardenrs/server:1.16.3
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /root/traefik-portenaire/trafik-data/bitwarden/data:/data
    ports:
      - "82:80"
    labels:
      - "traefik.enable=true"
#      - "traefik.docker.network=web"
#      - "traefik.port=80"
#      - "traefik.entryPoint=http"
#      - "traefik.backend=bitwarden"
      - "traefik.http.routers.bitwarden.entrypoints=http"
      - "traefik.http.routers.bitwarden.rule=Host(`dolivps.newtoncorp.fr`)"
      - "traefik.frontend.rule=Host:dolivps.newtoncorp.fr"
      - "traefik.http.middlewares.bitwarden-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.bitwarden.middlewares=traefik-https-redirect"
      - "traefik.http.routers.bitwarden-secure.entrypoints=https"
      - "traefik.http.routers.bitwarden-secure.rule=Host(`dolivps.newtoncorp.fr`)"
      - "traefik.http.routers.bitwarden-secure.tls=true"
      - "traefik.http.routers.bitwarden-secure.tls.certresolver=http"
      - "traefik.http.routers.bitwarden-secure.middlewares=traefik-auth"
      - "traefik.docker.network=traefik-proxy"
      - "traefik.http.services.bitwarden.loadbalancer.server.port=80"
      - "traefik.http.routers.bitwarden-secure.service=bitwarden"
    
#    networks:
#      - traefik-proxy
 

  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dolibarr
    networks:
      - traefik-proxy 

  dolibarr:
    image: tuxgasy/dolibarr
    environment:
      DOLI_DB_HOST: mariadb
      DOLI_DB_USER: root
      DOLI_DB_PASSWORD: root
      DOLI_DB_NAME: dolibarr
      DOLI_ADMIN_LOGIN: 'admin' 
      DOLI_ADMIN_PASSWORD: 'admin'
      DOLI_URL_ROOT: 'http://0.0.0.0'
      PHP_INI_DATE_TIMEZONE: 'Europe/Paris'
    ports:
      - "81:80"
      - "8080:8080"
    networks:
      - traefik-proxy
    links:
      - mariadb
#    labels:
#      - "traefik.enable=true"
#      - "traefik.http.routers.dolibarr.entrypoints=http"
#      - "traefik.http.routers.dolibarr.rule=Host(`dolivps.newtoncorp.fr`)"
#      - "traefik.http.middlewares.dolibarr-https-redirect.redirectscheme.scheme=https"
#      - "traefik.http.routers.dolibarr.middlewares=traefik-https-redirect"
#      - "traefik.http.routers.dolibarr-secure.entrypoints=https"
#      - "traefik.http.routers.dolibarr-secure.rule=Host(`dolivps.newtoncorp.fr`)"
#      - "traefik.http.routers.dolibarr-secure.middlewares=traefik-auth"
#      - "traefik.http.routers.dolibarr-secure.tls=true"
#      - "traefik.http.routers.dolibarr-secure.tls.certresolver=http"
#      - "traefik.docker.network=traefik-proxy"
#      - "traefik.http.services.dolibarr.loadbalancer.server.port=80"
#      - "traefik.http.routers.dolibarr-secure.service=dolibarr"


  database:
    image: mariadb:latest
    container_name: nextcloud_database
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: root
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: nextcloud
    networks:
      - traefik-proxy
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /root/traefik-portenaire/trafik-data/nextcloud/mysql:/mysql

  nextcloud:
#    depends_on:
#      - database
    image: nextcloud
    container_name: nextcloud_app
    restart: unless-stopped
    ports:
      - "83:80"
    environment:
      MYSQL_HOST: database
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: nextcloud
#      NEXTCLOUD_TRUSTED_DOMAINS=${NEXTCLOUD_URL}
    networks:
      - traefik-proxy
    links:
      - database
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /root/traefik-portenaire/trafik-data/nextcloud/html:/html
#    labels:
#      - "traefik.enable=true"
#      - "traefik.docker.network=traefik_network"
#      - "traefik.http.routers.nextcloud.entrypoints=web,websecure"
#      - "traefik.http.routers.nextcloud.rule=Host(`${NEXTCLOUD_URL}`)"
#      - "traefik.http.services.nextcloud.loadbalancer.server.port=80"
#      - "traefik.http.routers.nextcloud.tls=true"
#      - "traefik.http.routers.nextcloud.tls.certresolver=leresolver"


#  odoo:
#    image: odoo:latest
#    restart: unless-stopped
#    env_file: .env
#    depends_on:
#      - postgres
#    ports:
#      - "84:80"
#      - "8069:8069"
#    networks:
#      - traefik-proxy
#    volumes:
#      - /root/traefik-portenaire/trafik-data/odoo/data:/var/lib/odoo      
#  postgres:
#    image: postgres:13
#    restart: unless-stopped
#    env_file: .env
#    volumes:
#      - /root/traefik-portenaire/trafik-data/odoo/db:/var/lib/postgresql/data/pgdata    
#
#volumes:
#  data:
#  db:

#  db:
#    image: postgres:latest
#    ports:
#      - "5432:5432"
#    environment:
#      POSTGRES_DB: postgres
#      POSTGRES_PASSWORD: odoo
#      POSTGRES_USER: odoo
#      PGDATA: /var/lib/postgresql/data/pgdata
#    networks:
#      - traefik-proxy
#    volumes:
#      - /root/traefik-portenaire/trafik-data/odoo/odoo-db-data:/var/lib/postgresql/data/pgdata
#  odoo13:
#    image: odoo:latest
#    depends_on:
#      - db
#    ports:
#      - "84:80"
#      - "8069:8069"
#    links:
#      - db
#    restart: unless-stopped
#    networks:
#      - traefik-proxy
#    volumes:
#      - /etc/localtime:/etc/localtime:ro
#      - /var/run/docker.sock:/var/run/docker.sock:ro
#      - /root/traefik-portenaire/trafik-data/odoo/odoo-odoo13-data:/var/lib/odoo
#      - /root/traefik-portenaire/trafik-data/odoo/config_odoo_13:/etc/odoo
#      - /root/traefik-portenaire/trafik-data/odoo/aflowz_addons:/mnt/aflowz_addons
#    command: odoo --dev=reload
#    environment:
#      HOST: db
#      USER: odoo
#      PASSWORD: odoo
#    labels:
#      - "traefik.enable=true"
#      - "traefik.docker.network=traefik_network"


#volumes:
#  odoo-odoo13-data:
#  odoo-db-data:
#volumes:
#  mysql:
#  html:

#  web:
#    image: odoo:12.0
#    depends_on:
#      - db
#    ports:
#      - "8069:8069"
#    volumes:
#      - odoo-web-data:/var/lib/odoo
#      - ./config:/etc/odoo
#      - ./addons:/mnt/extra-addons
#  db:
#    image: postgres:10
#    environment:
#      - POSTGRES_DB=postgres
#      - POSTGRES_PASSWORD=odoo
#      - POSTGRES_USER=odoo
#      - PGDATA=/var/lib/postgresql/data/pgdata
#    volumes:
#      - odoo-db-data:/var/lib/postgresql/data/pgdata
#volumes:
#  odoo-web-data:
#  odoo-db-data:


  web:
    image: odoo:12.0
    depends_on:
      - mydb
    ports:
      - "86:80"
      - "8069:8069"
    environment:
    - HOST=mydb
    - USER=odoo
    - PASSWORD=myodoo
  mydb:
    image: postgres:10
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=myodoo
      - POSTGRES_USER=odoo


  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "85:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress

volumes:
  db_data: {}

networks:
  web:
  traefik-proxy:
    external: true
